Actividades/Angel leon/ruby on rails/aplicacion_db/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'usuario/index'
  get 'usuario/crear'
  post 'usuario/crear_u'
end

Actividades/Angel leon/ruby on rails/aplicacion_db/app/models/usuario.rb
class Usuario < ApplicationRecord

	def new

	end

end

Actividades/Angel leon/ruby on rails/aplicacion_db/app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
	def index

	end

	def crear

	end



	def crear_u
		 datos_usuario = params.require(:usuario).permit(:name,
		 												 :last_name,
		 												 :fecha_nacimiento,
		 												 :telefono,
		 												 :email)

		usuario = Usuario.new(datos_usuario)
		crear_usuario = usuario.save()

		if crear_usuario
			redirect_to controller: 'Usuario', action: 'ver'
		else

		end


     end
end

Actividades/Angel leon/ruby on rails/aplicacion_db/app/helpers/usuario_helper.rb
module UsuarioHelper
end

Actividades/Angel leon/ruby on rails/aplicacion_db/app/views/usuario/crear.html.erb
<!doctype html>
<html lang="en">
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<title>Crear usuario</title>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12 d-flex align-items-center mr-auto">
				<form class=""  action="<%= usuario_crear_u_path %>" method="POST" style="display: block;margin:0 auto;">
					<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
					<div class="form-group">
						<label for="exampleInputEmail1">Nombre</label>
						<input name="usuario[name]" type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Ingrese nombre ">
					</div>
					<div class="form-group">
						<label for="exampleInputPassword1">Apellido</label>
						<input name="usuario[last_name]" type="text" class="form-control"  placeholder="Apellido">
					</div>
					<div class="form-group">
						<label for="exampleInputEmail1">Fecha nacimiento</label>
						<input name="usuario[fecha_nacimiento]" type="date" class="form-control"  aria-describedby="emailHelp" placeholder="Fecha nacimiento">
					</div>
					<div class="form-group">
						<label for="exampleInputEmail1">Telefono</label>
						<input name="usuario[telefono]" type="number" class="form-control"  aria-describedby="emailHelp" placeholder="Telefono">
					</div>
						<div class="form-group">
						<label for="exampleInputEmail1">Correo</label>
						<input name="usuario[email]" type="text" class="form-control"  aria-describedby="emailHelp" placeholder="Correo electónico">
					</div>
					<button type="submit" class="btn btn-primary">Enviar</button>
				</form>
			</div>

		</div>
	</div>



	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Actividades/Angel leon/ruby on rails/aplicacion_db/app/views/usuario/index.html.erb
<h1>Hola</h1>